# Generated by Django 4.1.5 on 2023-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='chat.room'),
        ),
    ]
