# Generated by Django 4.1.5 on 2023-03-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_unreadmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
