# Generated by Django 4.1.2 on 2022-11-01 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(0, 'Organisation'), (1, 'Own business'), (2, 'User')], max_length=100)),
                ('work_regulations', models.IntegerField(choices=[(0, '---'), (1, 'Mon-Fri'), (2, 'Mon-Sun'), (3, 'Mon-Sat'), (4, 'Sun-Sat')], default=0, null=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('meeting_type', models.IntegerField(choices=[(0, '---'), (1, '15m'), (2, '30m'), (3, '45m'), (4, '1h'), (5, '1d')], default=0, null=True)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('adress', models.TextField()),
                ('calendar_scope', models.IntegerField(choices=[(0, 'all'), (1, 'only friends'), (2, 'only me')])),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
