# Generated by Django 4.1.2 on 2022-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/default-car.png', null=True, upload_to='images/'),
        ),
    ]
