# Generated by Django 4.1.5 on 2023-01-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
