# Generated by Django 4.1.5 on 2023-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day_available_places',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meeting_type',
            field=models.IntegerField(choices=[(0, '---'), (15, '15m'), (30, '30m'), (45, '45m'), (60, '1h'), (1, '1d')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_regulations',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Mon-Fri'), (2, 'Mon-Sun'), (3, 'Mon-Sat'), (4, 'Sun-Sat')], default=1, null=True),
        ),
    ]
