# Generated by Django 4.1.5 on 2023-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_facebook_profile_github_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.profile'),
        ),
    ]
