# Generated by Django 4.1.7 on 2023-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_options_employee_profile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='responsibilities',
            field=models.TextField(null=True),
        ),
    ]
