# Generated by Django 4.1.5 on 2023-01-23 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 10, 45, 31, 757475, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='day',
            name='available_places',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='count_meetings',
            field=models.IntegerField(default=0),
        ),
    ]
