# Generated by Django 4.1.5 on 2023-01-23 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0002_meetings_date_alter_day_available_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
