# Generated by Django 4.1.2 on 2022-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0002_meetings_message_meetings_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='count_meetings',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='day',
        ),
        migrations.AddField(
            model_name='meetings',
            name='day',
            field=models.ManyToManyField(to='calendar_manager.day'),
        ),
    ]
