# Generated by Django 4.1.7 on 2023-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0004_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
