# Generated by Django 4.1.7 on 2023-03-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0005_alter_posts_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
